### ISSUE TITLE
cant pass the output of nomad-pack render to file

### ISSUE THREAD

**Issue by attachmentgenie** [hashicorp/nomad-pack#163] opened 2021-11-04 10:36 UTC
The following commands all yield an empty jenkins.nomad

`
nomad-pack render jenkins -f jenkins/vars.nomad > jenkins.nomad
nomad-pack render jenkins -f jenkins/vars.nomad &> jenkins.nomad
nomad-pack render jenkins -f jenkins/vars.nomad 2>&1 | tee jenkins.noma
nomad-pack render jenkins -f jenkins/vars.nomad | tee jenkins.nomad
nomad-pack render jenkins -f jenkins/vars.nomad |& tee jenkins.nomad
`

**Comment by tgross** [comment] 2021-11-05 18:00
I can confirm this as I just ran into it myself. Looks like we're calling `RenderFrame` in the library we're using github.com/mitchellh/go-glint; I'm not sure this is appropriate for non-interactive invocation CLI.

**Comment by tgross** [comment] 2021-11-05 18:42
Well there's our problem: https://github.com/mitchellh/go-glint#roadmap
> **Non-interactive interfaces.** We want to add support for rendering to non-interactive interfaces and allowing components to provide custom behavior in these cases. For now, users of Glint should detect non-interactivity and avoid using Glint.

We probably shouldn't be using Glint outputs for many of the output commands here.

**Comment by tgross** [comment] 2021-11-09 15:20
@attachmentgenie I've been told this is intentional, as nomad-pack can render multiple files in a single invocation (see https://github.com/hashicorp/nomad-pack/pull/168#issuecomment-964160136). So having the shell redirect doesn't really work.

**Comment by rigrassm** [comment] 2021-11-09 16:46
I was looking at this a couple weeks ago and was thinking that a potential solution would be to add a boolean flag like `--render-to-files` and then just have the renders each be redirected to a file with the name of the template sans the `.tpl` extension.

**Comment by angrycub** [comment] 2022-02-14 18:00
Closed in #168

**Closed by angrycub** 2022-02-14 18:00 UTC
Labels: type/bug, stage/accepted, theme/cli
